#!/usr/bin/env npx ts-node

/**
 * Script to download Codex instructions from GitHub and generate TypeScript source code.
 *
 * Usage:
 *   npx ts-node scripts/generate-codex-instructions.ts
 *
 * This script:
 * 1. Fetches the latest Codex release tag from GitHub
 * 2. Downloads all Codex instruction files
 * 3. Generates src/oauth/ai-sdk-providers/codex-instructions.ts with embedded instructions
 */

import * as fs from "fs";
import * as path from "path";

const CODEX_GITHUB_API_RELEASES =
  "https://api.github.com/repos/openai/codex/releases/latest";
const CODEX_GITHUB_HTML_RELEASES =
  "https://github.com/openai/codex/releases/latest";

// Model family -> prompt file mapping
const CODEX_PROMPT_FILES: Record<string, string> = {
  "gpt-5.2-codex": "gpt-5.2-codex_prompt.md",
  "codex-max": "gpt-5.1-codex-max_prompt.md",
  codex: "gpt_5_codex_prompt.md",
  "gpt-5.2": "gpt_5_2_prompt.md",
  "gpt-5.1": "gpt_5_1_prompt.md",
};

// Output file path
const OUTPUT_FILE = path.join(
  __dirname,
  "..",
  "src",
  "oauth",
  "ai-sdk-providers",
  "codex-instructions.ts",
);

async function getLatestCodexTag(): Promise<string> {
  console.log("Fetching latest Codex release tag...");

  try {
    // Try API first
    const apiResponse = await fetch(CODEX_GITHUB_API_RELEASES);
    if (apiResponse.ok) {
      const data = (await apiResponse.json()) as { tag_name?: string };
      if (data.tag_name) {
        console.log(`  Found tag via API: ${data.tag_name}`);
        return data.tag_name;
      }
    }
  } catch {
    console.log("  API fetch failed, trying HTML fallback...");
  }

  // Fallback: follow redirect from HTML page
  const htmlResponse = await fetch(CODEX_GITHUB_HTML_RELEASES, {
    redirect: "follow",
  });
  if (!htmlResponse.ok) {
    throw new Error(`Failed to fetch latest release: ${htmlResponse.status}`);
  }

  const finalUrl = htmlResponse.url;
  if (finalUrl) {
    const parts = finalUrl.split("/");
    const last = parts[parts.length - 1];
    if (last && !last.includes("/")) {
      console.log(`  Found tag via redirect: ${last}`);
      return last;
    }
  }

  const html = await htmlResponse.text();
  const match = html.match(/\/openai\/codex\/releases\/tag\/([^"]+)/);
  if (match) {
    console.log(`  Found tag via HTML: ${match[1]}`);
    return match[1];
  }

  throw new Error("Failed to determine latest release tag from GitHub");
}

async function downloadInstructions(
  tag: string,
  promptFile: string,
): Promise<string> {
  const url = `https://raw.githubusercontent.com/openai/codex/${tag}/codex-rs/core/${promptFile}`;
  console.log(`  Downloading ${promptFile}...`);

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to download ${promptFile}: ${response.status}`);
  }

  return response.text();
}

function escapeForTemplate(str: string): string {
  // Escape backticks and ${} for template literal
  return str
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

async function main() {
  console.log("=".repeat(60));
  console.log("Codex Instructions Generator");
  console.log("=".repeat(60));

  // Step 1: Get latest tag
  const tag = await getLatestCodexTag();
  console.log(`\nUsing Codex release: ${tag}\n`);

  // Step 2: Download all instruction files
  const instructions: Record<string, string> = {};

  for (const [family, promptFile] of Object.entries(CODEX_PROMPT_FILES)) {
    try {
      instructions[family] = await downloadInstructions(tag, promptFile);
      console.log(`    ✓ ${family}: ${instructions[family].length} chars`);
    } catch (err) {
      console.error(`    ✗ ${family}: ${err}`);
      // Use fallback for missing files
      instructions[family] = "";
    }
  }

  // Step 3: Generate TypeScript source code
  console.log("\nGenerating TypeScript source code...");

  const generatedCode = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file contains Codex instructions fetched from GitHub.
 * Generated by: scripts/generate-codex-instructions.ts
 * Codex release: ${tag}
 * Generated at: ${new Date().toISOString()}
 *
 * To update, run: npx ts-node scripts/generate-codex-instructions.ts
 */

// Codex release version used
export const CODEX_VERSION = "${tag}";

// Instructions by model family
export const CODEX_INSTRUCTIONS: Record<string, string> = {
${Object.entries(instructions)
  .map(([family, content]) => {
    if (!content) {
      return `  "${family}": "",`;
    }
    return `  "${family}": \`${escapeForTemplate(content)}\`,`;
  })
  .join("\n\n")}
};

/**
 * Get the model family from a model name.
 */
export function getModelFamily(model: string): string {
  const modelLower = model.toLowerCase();

  if (modelLower.includes("gpt-5.2-codex") || modelLower.includes("gpt 5.2 codex")) {
    return "gpt-5.2-codex";
  }
  if (modelLower.includes("codex-max") || modelLower.includes("codex max")) {
    return "codex-max";
  }
  if (modelLower.includes("codex") || modelLower.startsWith("codex-")) {
    return "codex";
  }
  if (modelLower.includes("gpt-5.2") || modelLower.includes("gpt 5.2")) {
    return "gpt-5.2";
  }
  return "gpt-5.1";
}

/**
 * Get Codex instructions for a model.
 * Falls back to gpt-5.1 instructions if specific instructions not found.
 */
export function getCodexInstructions(model: string): string {
  const family = getModelFamily(model);
  const instructions = CODEX_INSTRUCTIONS[family];

  if (instructions) {
    return instructions;
  }

  // Fallback to gpt-5.1
  return CODEX_INSTRUCTIONS["gpt-5.1"] || "";
}
`;

  // Step 4: Write to file
  fs.writeFileSync(OUTPUT_FILE, generatedCode);
  console.log(`\nGenerated: ${OUTPUT_FILE}`);
  console.log(`File size: ${generatedCode.length} bytes`);

  // Step 5: Summary
  console.log("\n" + "=".repeat(60));
  console.log("SUMMARY");
  console.log("=".repeat(60));
  console.log(`Codex version: ${tag}`);
  console.log(`Output file: ${OUTPUT_FILE}`);
  console.log("\nInstructions by family:");
  for (const [family, content] of Object.entries(instructions)) {
    console.log(`  ${family}: ${content.length} chars`);
  }

  console.log("\n✓ Done! Now rebuild the extension with: yarn build");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
